---
- hosts: all
  become: yes
  tasks:
    - name: Install gcc
      apt:
        name: gcc
        state: present
        update_cache: yes

    - name: Install glibc
      apt:
        name: libc6
        state: present

    - name: Install glibc-devel
      apt:
        name: libc6-dev
        state: present

    - name: Install libgcc_s1
      apt:
        name: libgcc1
        state: present

    - name: Install libstdc++6
      apt:
        name: libstdc++6
        state: present

    - name: Copy IBM COBOL installation files to remote server
      copy:
        src: /Users/rajrajar/vault/mainframe/IBM_COBOL_V1.2.0_LINUX_EVAL.x86-64.240110.tar.gz
        dest: /tmp/ibm_cobol_installation_files.tar.gz

    - name: Create directory for IBM COBOL installation files
      file:
        path: /tmp/ibm_cobol_installation_files
        state: directory

    - name: Extract IBM COBOL installation files
      unarchive:
        src: /tmp/ibm_cobol_installation_files.tar.gz
        dest: /tmp/ibm_cobol_installation_files
        remote_src: yes

    - name: Run IBM COBOL installation script
      command:
        cmd: /tmp/ibm_cobol_installation_files/install
        
    - name: Create symbolic link for cob2
      file:
        src: /opt/ibm/cobol/1.2.0/usr/bin/cob2
        dest: /usr/bin/cob2
        state: link

    - name: Create symbolic link for cob2.cfg
      file:
        src: /opt/ibm/cobol/1.2.0/etc/cob2.cfg
        dest: /etc/cob2.cfg
        state: link

    - name: Add IBM COBOL paths to PATH environment variable
      lineinfile:
        path: /home/adminuser/.bashrc
        line: 'export PATH=$PATH:/opt/ibm/cobol/1.2.0/bin:/opt/ibm/cobol/rte/bin:/opt/ibm/cobol/debug/usr/bin'
        state: present

    - name: Source .bashrc to update PATH environment variable
      shell: source /home/adminuser/.bashrc
      args:
        executable: /bin/bash

    - name: SFTP DB2 Community Edition installation files
      synchronize:
        src: /Users/rajrajar/vault/mainframe/v11.5.9_linuxx64_server_dec.tar.gz
        dest: /tmp/db2_installation_files.tar.gz
        mode: push

    - name: Create directory for IBM DB2 installation files
      file:
        path: /tmp/db2_installation_files
        state: directory

    - name: Extract DB2 installation files
      unarchive:
        src: /tmp/db2_installation_files.tar.gz
        dest: /tmp/db2_installation_files
        remote_src: yes

    - name: Run DB2 installation script
      command:
        cmd: /tmp/db2_installation_files/server_dec/db2_install
        # creates: /path/to/installed/db2